apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: Calculator_App
  description: Everything related to calculator
  tags:
    - portal
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  owner: Team-A
  domain: calculator