apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: api
  description: Calculator APi
spec:
  type: openapi
  lifecycle: production
  owner: Team-A
  system: Calculator_App
  definition:
    $text: https://raw.githubusercontent.com/kanikamittal09/bazel-demo/master/openapi/calculator.swagger.json